# Generated by Django 5.0.11 on 2025-02-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
    ]
