# Generated by Django 5.0.11 on 2025-02-04 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_assign_default_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tourist Destination', 'verbose_name_plural': 'Tourist Destinations'},
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(help_text='Detailed description of the location'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(help_text='District or county', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='google_map_link',
            field=models.URLField(help_text='Google Maps embed URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(help_text='Featured image for the destination', upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='place_name',
            field=models.CharField(help_text='Name of the tourist destination', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(help_text='State or province location', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='weather',
            field=models.CharField(help_text='Typical weather conditions', max_length=100),
        ),
    ]
