# Generated by Django 5.0.11 on 2025-02-05 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_options_destination_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_destinations', to=settings.AUTH_USER_MODEL, verbose_name='Favorited By'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['place_name', 'state'], name='destination_place_n_3e35c9_idx'),
        ),
    ]
